import React, { useEffect, useState, useCallback } from 'react';
import {
  View, Text, ScrollView, StyleSheet, TouchableOpacity, ActivityIndicator, Alert,
} from 'react-native';
import { Course, Profile } from '../../../types';
import { CourseSyllabus, AISuggestion, AISuggestionType } from '../../../types/courseManagement';
import { getAllAIAnalysisForCourse } from '../../../services/courseManagement';
import { getMockAISuggestions } from '../../../utils/aiPlaceholder';

const C = {
  forest: '#1A5C38', leaf: '#3A8F5F', mist: '#F2FAF5',
  ink: '#1A1A1A', inkMid: 'rgba(26,26,26,0.65)', inkSoft: 'rgba(26,26,26,0.4)',
  border: '#E0EDE6', card: '#FFFFFF', green50: '#F0F6EF',
  red: '#D9534F', redBg: '#FDF1F1',
  amber: '#92600A', amberBg: '#FFFBEB', amberBdr: '#FDE68A',
  blue: '#1D4ED8', blueBg: '#EFF6FF',
  purple: '#7C3AED', purpleBg: '#F5F3FF', purpleBdr: '#DDD6FE',
};

const SUGGESTION_META: Record<AISuggestionType, { icon: string; color: string; bg: string }> = {
  replace_topic:    { icon: '🔄', color: C.blue,   bg: C.blueBg   },
  move_semester:    { icon: '📅', color: C.purple, bg: C.purpleBg },
  change_outcome:   { icon: '🎯', color: C.forest, bg: C.green50  },
  reduce_content:   { icon: '✂️',  color: C.amber,  bg: C.amberBg  },
  notify_professor: { icon: '💬', color: C.blue,   bg: C.blueBg   },
  request_admin:    { icon: '🛡️',  color: C.red,    bg: C.redBg    },
};

interface Props {
  course: Course;
  profile: Profile;
  syllabus: CourseSyllabus | null;
}

const AISuggestionsTab: React.FC<Props> = ({ course, profile, syllabus }) => {
  const [suggestions, setSuggestions] = useState<AISuggestion[]>([]);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      setSuggestions(getMockAISuggestions(course.id) as AISuggestion[]);
    } catch {
      setSuggestions(getMockAISuggestions(course.id) as AISuggestion[]);
    } finally {
      setLoading(false);
    }
  }, [course.id]);

  useEffect(() => { load(); }, [load]);

  const handleAction = (suggestion: AISuggestion) => {
    if (suggestion.type === 'notify_professor' && suggestion.related_professor_name) {
      Alert.alert(
        'Message Professor',
        `Open a message to ${suggestion.related_professor_name} about overlap in "${suggestion.related_course_name}"?\n\nGo to the Overlap Reports tab to send the message.`,
        [{ text: 'OK' }],
      );
    } else if (suggestion.type === 'request_admin') {
      Alert.alert(
        'Request Administrator Approval',
        'This action requires administrator review. A request will be sent to the admin with the AI suggestion and your course details.',
        [
          { text: 'Cancel', style: 'cancel' },
          { text: 'Send Request', onPress: () => Alert.alert('Request Sent', 'The administrator has been notified.') },
        ],
      );
    } else {
      Alert.alert(
        suggestion.title,
        suggestion.description + '\n\nThis suggestion requires updating your syllabus or materials. Use the Syllabus Check tab to submit changes.',
        [{ text: 'OK' }],
      );
    }
  };

  if (loading) {
    return <View style={s.centre}><ActivityIndicator color={C.leaf} size="large" /></View>;
  }

  if (!syllabus || syllabus.status === 'none') {
    return (
      <View style={s.centre}>
        <Text style={s.lockIcon}>🤖</Text>
        <Text style={s.lockTitle}>No Analysis Yet</Text>
        <Text style={s.lockBody}>
          AI suggestions appear after the syllabus is locked and materials are uploaded.
          Upload your syllabus and wait for administrator approval to begin.
        </Text>
      </View>
    );
  }

  return (
    <ScrollView contentContainerStyle={s.content}>
      {/* Header note */}
      <View style={s.headerNote}>
        <Text style={s.headerNoteText}>
          🤖  These suggestions are generated by AI based on your uploaded documents,{' '}
          {'{accreditation}'} standards, program learning outcomes, and content from other
          courses across the institution. Suggestions cannot be ignored — they must be
          acted on or escalated to the administrator.
        </Text>
      </View>

      {suggestions.length === 0 && (
        <View style={s.empty}>
          <Text style={s.emptyIcon}>✨</Text>
          <Text style={s.emptyTitle}>No Suggestions Yet</Text>
          <Text style={s.emptyText}>
            Run AI analysis on your syllabus or course materials to generate suggestions.
          </Text>
        </View>
      )}

      {/* Group by type */}
      {Object.entries(
        suggestions.reduce((acc, sug) => {
          if (!acc[sug.type]) acc[sug.type] = [];
          acc[sug.type].push(sug);
          return acc;
        }, {} as Record<AISuggestionType, AISuggestion[]>),
      ).map(([type, sugs]) => {
        const meta = SUGGESTION_META[type as AISuggestionType];
        const typeLabel: Record<AISuggestionType, string> = {
          replace_topic:    'Replace / Reframe Topic',
          move_semester:    'Move to Different Semester',
          change_outcome:   'Revise Learning Outcome',
          reduce_content:   'Reduce / Restructure Content',
          notify_professor: 'Coordinate with Another Professor',
          request_admin:    'Requires Administrator Approval',
        };
        return (
          <View key={type} style={s.group}>
            <View style={[s.groupHeader, { backgroundColor: meta.bg }]}>
              <Text style={s.groupHeaderIcon}>{meta.icon}</Text>
              <Text style={[s.groupHeaderLabel, { color: meta.color }]}>
                {typeLabel[type as AISuggestionType]}
              </Text>
              <View style={[s.groupCount, { backgroundColor: meta.color }]}>
                <Text style={s.groupCountText}>{sugs.length}</Text>
              </View>
            </View>
            {sugs.map(sug => (
              <SuggestionCard key={sug.id} suggestion={sug} meta={meta} onAction={() => handleAction(sug)} />
            ))}
          </View>
        );
      })}

      {/* Disclaimer */}
      <View style={s.disclaimer}>
        <Text style={s.disclaimerText}>
          ⚠️  Suggestions generated by AI are advisory and based on your institution's accreditation
          framework. You cannot delete or dismiss suggestions. Contact your administrator if you
          believe a suggestion is incorrect.
        </Text>
      </View>
    </ScrollView>
  );
};

interface SuggestionCardProps {
  suggestion: AISuggestion;
  meta: { icon: string; color: string; bg: string };
  onAction: () => void;
}

const SuggestionCard: React.FC<SuggestionCardProps> = ({ suggestion, meta, onAction }) => (
  <View style={[s.card, { borderLeftColor: meta.color }]}>
    <Text style={s.cardTitle}>{suggestion.title}</Text>
    {(suggestion.related_professor_name || suggestion.related_course_name) && (
      <View style={s.relatedRow}>
        {suggestion.related_professor_name && (
          <Text style={s.relatedTag}>👤 {suggestion.related_professor_name}</Text>
        )}
        {suggestion.related_course_name && (
          <Text style={s.relatedTag}>📘 {suggestion.related_course_name}</Text>
        )}
      </View>
    )}
    <Text style={s.cardDesc}>{suggestion.description}</Text>
    <TouchableOpacity style={[s.actionBtn, { borderColor: meta.color }]} onPress={onAction}>
      <Text style={[s.actionBtnText, { color: meta.color }]}>{suggestion.action_label}</Text>
    </TouchableOpacity>
  </View>
);

const s = StyleSheet.create({
  content: { padding: 16, paddingBottom: 40 },
  centre:  { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32 },
  lockIcon:  { fontSize: 48, marginBottom: 12 },
  lockTitle: { fontSize: 18, fontWeight: '700', color: C.ink, marginBottom: 8, textAlign: 'center' },
  lockBody:  { fontSize: 13, color: C.inkMid, textAlign: 'center', lineHeight: 19 },

  headerNote: {
    backgroundColor: C.green50, borderWidth: 1, borderColor: C.border,
    borderRadius: 8, padding: 12, marginBottom: 16,
  },
  headerNoteText: { fontSize: 12, color: C.inkMid, lineHeight: 17 },

  empty:     { alignItems: 'center', padding: 32 },
  emptyIcon: { fontSize: 40, marginBottom: 10 },
  emptyTitle:{ fontSize: 16, fontWeight: '700', color: C.ink, marginBottom: 6 },
  emptyText: { fontSize: 13, color: C.inkMid, textAlign: 'center', lineHeight: 19 },

  group:       { marginBottom: 16 },
  groupHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 8, padding: 10, marginBottom: 8 },
  groupHeaderIcon:  { fontSize: 18 },
  groupHeaderLabel: { flex: 1, fontSize: 13, fontWeight: '700' },
  groupCount:  { borderRadius: 10, paddingHorizontal: 8, paddingVertical: 2 },
  groupCountText: { color: '#fff', fontSize: 11, fontWeight: '700' },

  card: {
    backgroundColor: C.card, borderWidth: 1, borderColor: C.border, borderLeftWidth: 3,
    borderRadius: 10, padding: 14, marginBottom: 8,
    shadowColor: '#000', shadowOpacity: 0.04, shadowRadius: 6, elevation: 2,
  },
  cardTitle:   { fontSize: 14, fontWeight: '700', color: C.ink, marginBottom: 4 },
  relatedRow:  { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 6 },
  relatedTag:  { fontSize: 11, color: C.inkMid, backgroundColor: C.mist, borderRadius: 10, paddingHorizontal: 8, paddingVertical: 2 },
  cardDesc:    { fontSize: 13, color: C.inkMid, lineHeight: 19, marginBottom: 10 },
  actionBtn:   { alignSelf: 'flex-start', borderWidth: 1.5, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 7 },
  actionBtnText: { fontSize: 12, fontWeight: '700' },

  disclaimer: {
    backgroundColor: C.amberBg, borderWidth: 1, borderColor: C.amberBdr,
    borderRadius: 8, padding: 12, marginTop: 8,
  },
  disclaimerText: { fontSize: 11, color: C.amber, lineHeight: 17 },
});

export default AISuggestionsTab;
