import { HomeworkAlignmentCheck, HomeworkGradingBatch, HomeworkStudentResult } from '../types/homeworkAssistance';

// ── Alignment result export ────────────────────────────────────────────────────

export const exportAlignmentResultAsText = (check: HomeworkAlignmentCheck): string => {
  const lines: string[] = [];
  const divider = '─'.repeat(60);

  lines.push('HOMEWORK ALIGNMENT CHECK REPORT');
  lines.push(divider);
  lines.push(`Course: ${check.course_name}`);
  lines.push(`Homework Title: ${check.homework_title}`);
  lines.push(`Date: ${new Date(check.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`);
  lines.push('');

  lines.push('ALIGNMENT SCORE');
  lines.push(divider);
  lines.push(`Overall Alignment: ${check.alignment_percentage}%`);
  const statusLabel: Record<string, string> = {
    strongly_aligned: 'Strongly Aligned',
    mostly_aligned: 'Mostly Aligned',
    partially_aligned: 'Partially Aligned',
    not_aligned: 'Not Aligned',
  };
  lines.push(`Status: ${statusLabel[check.alignment_status] ?? check.alignment_status}`);
  lines.push('');

  if (check.covered_learning_objectives.length > 0) {
    lines.push('COVERED LEARNING OBJECTIVES');
    lines.push(divider);
    check.covered_learning_objectives.forEach(obj => lines.push(`  ✓ ${obj}`));
    lines.push('');
  }

  if (check.missing_learning_objectives.length > 0) {
    lines.push('MISSING LEARNING OBJECTIVES');
    lines.push(divider);
    check.missing_learning_objectives.forEach(obj => lines.push(`  ✗ ${obj}`));
    lines.push('');
  }

  lines.push('SYLLABUS ALIGNMENT SUMMARY');
  lines.push(divider);
  lines.push(check.syllabus_alignment_summary);
  lines.push('');

  lines.push('SCHEME OF WORK ALIGNMENT SUMMARY');
  lines.push(divider);
  lines.push(check.scheme_of_work_alignment_summary);
  lines.push('');

  lines.push('ACCREDITATION ALIGNMENT SUMMARY');
  lines.push(divider);
  lines.push(check.accreditation_alignment_summary);
  lines.push('');

  lines.push('PROGRAM OUTCOMES ALIGNMENT SUMMARY');
  lines.push(divider);
  lines.push(check.program_alignment_summary);
  lines.push('');

  if (check.overlap_detected && check.overlap_details.length > 0) {
    lines.push('OVERLAP WITH OTHER COURSES');
    lines.push(divider);
    check.overlap_details.forEach(o => {
      lines.push(`  Course: ${o.course_name}${o.professor_name ? ` (${o.professor_name})` : ''}`);
      lines.push(`  Severity: ${o.severity.toUpperCase()}`);
      lines.push(`  Description: ${o.overlap_description}`);
      lines.push('');
    });
  }

  if (check.ai_recommendations.length > 0) {
    lines.push('AI RECOMMENDATIONS');
    lines.push(divider);
    check.ai_recommendations.forEach((rec, i) => lines.push(`  ${i + 1}. ${rec}`));
    lines.push('');
  }

  if (check.suggested_revised_homework) {
    lines.push('SUGGESTED REVISED HOMEWORK');
    lines.push(divider);
    lines.push(check.suggested_revised_homework);
    lines.push('');
  }

  if (check.generated_tasks.length > 0) {
    lines.push('GENERATED ACTION TASKS');
    lines.push(divider);
    check.generated_tasks.forEach((task, i) => {
      lines.push(`  ${i + 1}. [${task.priority.toUpperCase()}] ${task.title}`);
      lines.push(`     ${task.description}`);
    });
    lines.push('');
  }

  lines.push(divider);
  lines.push('Generated by High Five — Homework Assistance');

  return lines.join('\n');
};

// ── Student grading result export ──────────────────────────────────────────────

export const exportGradingResultAsText = (
  result: HomeworkStudentResult,
  batchTitle: string,
): string => {
  const lines: string[] = [];
  const divider = '─'.repeat(60);
  const finalGrade = result.professor_edited_grade ?? result.overall_suggested_grade;

  lines.push('HOMEWORK GRADING REPORT');
  lines.push(divider);
  lines.push(`Assignment: ${batchTitle}`);
  lines.push(`Student: ${result.student_name}`);
  lines.push(`Overall Grade: ${finalGrade}/100`);
  lines.push(`Status: ${result.professor_status.charAt(0).toUpperCase() + result.professor_status.slice(1)}`);
  lines.push(`Date: ${new Date(result.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`);
  lines.push('');

  if (result.rubric_criterion_grades.length > 0) {
    lines.push('RUBRIC BREAKDOWN');
    lines.push(divider);
    const headers = ['Criterion', 'Max', 'Score', 'Explanation'];
    lines.push(headers.join(' | '));
    lines.push('─'.repeat(80));
    result.rubric_criterion_grades.forEach(r => {
      lines.push(`${r.criterion} | ${r.max_score} | ${r.suggested_score} | ${r.explanation}`);
    });
    lines.push('');
  }

  lines.push('GRADE JUSTIFICATION');
  lines.push(divider);
  lines.push(result.grade_justification);
  lines.push('');

  if (result.strengths.length > 0) {
    lines.push('STRENGTHS');
    lines.push(divider);
    result.strengths.forEach(s => lines.push(`  + ${s}`));
    lines.push('');
  }

  if (result.weaknesses.length > 0) {
    lines.push('AREAS FOR IMPROVEMENT');
    lines.push(divider);
    result.weaknesses.forEach(w => lines.push(`  - ${w}`));
    lines.push('');
  }

  if (result.missing_requirements.length > 0) {
    lines.push('MISSING REQUIREMENTS');
    lines.push(divider);
    result.missing_requirements.forEach(m => lines.push(`  ! ${m}`));
    lines.push('');
  }

  lines.push('ORIGINALITY ASSESSMENT');
  lines.push(divider);
  lines.push(result.plagiarism_risk_summary);
  lines.push('');

  const feedback = result.professor_edited_feedback ?? result.student_feedback_draft;
  if (feedback) {
    lines.push('STUDENT FEEDBACK');
    lines.push(divider);
    lines.push(feedback);
    lines.push('');
  }

  lines.push(divider);
  lines.push('Generated by High Five — Homework Assistance');

  return lines.join('\n');
};

// ── Clipboard ─────────────────────────────────────────────────────────────────

export const copyToClipboard = async (text: string): Promise<void> => {
  try {
    // Try React Native clipboard
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const Clipboard = require('@react-native-clipboard/clipboard').default;
    Clipboard.setString(text);
    return;
  } catch {
    // Fall through to web API
  }

  try {
    if (typeof navigator !== 'undefined' && navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return;
    }
  } catch {
    // Fall through to document.execCommand
  }

  // Last resort for older browsers
  try {
    const el = document.createElement('textarea');
    el.value = text;
    el.style.position = 'fixed';
    el.style.opacity = '0';
    document.body.appendChild(el);
    el.focus();
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);
  } catch {
    throw new Error('Clipboard not available on this device.');
  }
};

// ── Batch CSV export ──────────────────────────────────────────────────────────

const csvEsc = (val: string | number | undefined): string => {
  const s = String(val ?? '').replace(/\r?\n/g, ' ');
  return s.includes(',') || s.includes('"') || s.includes("'")
    ? `"${s.replace(/"/g, '""')}"`
    : s;
};

export const exportBatchAsCSV = (batch: HomeworkGradingBatch): string => {
  const headers = [
    'Student Name',
    'Matched Student ID',
    'Match Confidence',
    'Course',
    'Assignment',
    'Grade Points',
    'Total Points',
    'Grade %',
    'Status',
    'Strengths',
    'Weaknesses',
    'Improvement Recommendations',
    'Missing Requirements',
    'Feedback',
    'Professor Note',
    'Date',
  ];

  const rows = batch.student_results.map(r => {
    const grade    = r.professor_edited_grade ?? r.overall_suggested_grade;
    const points   = r.grade_points   ?? grade;
    const total    = r.total_points   ?? 100;
    const feedback = r.professor_edited_feedback ?? r.student_feedback_draft;
    return [
      csvEsc(r.student_name),
      csvEsc(r.student_id ?? ''),
      csvEsc(r.match_confidence ?? 'pending'),
      csvEsc(batch.course_name),
      csvEsc(batch.assignment_title),
      csvEsc(points),
      csvEsc(total),
      csvEsc(`${grade}%`),
      csvEsc(r.professor_status),
      csvEsc(r.strengths.join('; ')),
      csvEsc(r.weaknesses.join('; ')),
      csvEsc((r.improvement_recommendations ?? []).join('; ')),
      csvEsc(r.missing_requirements.join('; ')),
      csvEsc(feedback),
      csvEsc(r.professor_note ?? ''),
      csvEsc(new Date(r.created_at).toLocaleDateString('en-GB')),
    ];
  });

  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
};

export const copyBatchCSV = async (batch: HomeworkGradingBatch): Promise<void> => {
  const csv = exportBatchAsCSV(batch);
  await copyToClipboard(csv);
};

// ── PDF / Word export stubs ────────────────────────────────────────────────────

export const exportAsPdf = (_content: string): void => {
  alert('PDF export feature coming soon. Use "Copy as Text" in the meantime.');
};

export const exportAsWord = (_content: string): void => {
  alert('Word document export feature coming soon. Use "Copy as Text" in the meantime.');
};
